// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyUp0wy9psDCtT1WgjAJniLG_yqHacAA',
    appId: '1:661723357168:android:790fb202790fd7ce6f4735',
    messagingSenderId: '661723357168',
    projectId: 'link-up-6f5b6',
    storageBucket: 'link-up-6f5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0RU8w4fOUWjFY4FycXq3VorXiGV0UWw',
    appId: '1:661723357168:ios:bc2c4c474ba8d9b36f4735',
    messagingSenderId: '661723357168',
    projectId: 'link-up-6f5b6',
    storageBucket: 'link-up-6f5b6.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vHywutRFJnVDRikfYopip1kpwPy2Wj0',
    appId: '1:661723357168:web:6c5d4d0780b948b56f4735',
    messagingSenderId: '661723357168',
    projectId: 'link-up-6f5b6',
    authDomain: 'link-up-6f5b6.firebaseapp.com',
    storageBucket: 'link-up-6f5b6.firebasestorage.app',
    measurementId: 'G-J4DE468ECX',
  );
}
